
require "magick_flags/austria"
require "magick_flags/chile"
require "magick_flags/colombia"
require "magick_flags/denmark"
require "magick_flags/england"
require "magick_flags/finland"
require "magick_flags/italy"
require "magick_flags/japan"
require "magick_flags/poland"
require "magick_flags/spain"
require "magick_flags/switzerland"
